### ISSUE TITLE
[Bug] Hilfe bei Nutzung der Vorlage

### ISSUE THREAD

**Issue by Nica-Systems** [creativetimofficial/ct-vision-ui-dashboard-pro-react#3]
### Version
1.0.0
### Reproduction link
https://codepen.io/nica-systems/pen/jOayWBp
### Operating System
Windows 11
### Device
Computer
### Browser & Version
Microsoft Edge 2022
### Steps to reproduce
Guten Tag,

das Produkt wird leider nicht so ausgeführt, wie es eigentlich sollte.
### What is expected?
Ich möchte einen reibungslosen Startprozess.
### What is actually happening?
Mein Programm enthält einige Fehler, die den Startvorgang blockieren.

---

**Comment by simmmpleweb** [comment]
Hello, @Nica-Systems! Thanks for using our products! We need a little more information so we can help you out! Maybe check [this closed issue](https://github.com/creativetimofficial/ct-vision-ui-dashboard-pro-react/issues/1) and see if that helps! Regards, Vlad.
