### ISSUE TITLE
[Bug] Set up issue 

### ISSUE THREAD

**Issue by Naanncy** [creativetimofficial/ct-vision-ui-dashboard-pro-react#6]
### Version
1.0.2
### Reproduction link
https://va2pt.com
### Operating System
Ubuntu 22.04
### Device
ThinkPad
### Browser & Version
Chrome&Version 122.0.6261.94 (Official Build) (64-bit)
### Steps to reproduce
Till now i have just clone your project and trying to start with npm start and there are so many error which i have mentioned below 
1.Issue with sidenavCollapse.js-Line 123:32: 'info' is not defined.
2.React Hook useContext Called Conditionally.
3.Stylis Plugin RTL Warning -
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js): Failed to parse source map from '/home/thinkpad/frontendvision/node_modules/stylis-plugin-rtl/src/stylis-rtl.ts' file: Error: ENOENT: no such file or directory, open '/home/thinkpad/frontendvision/node_modules/stylis-plugin-rtl/src/stylis-rtl.ts'.
4.Module Warning for React Tag Input.
5.Module Not Found Error for VuiEditor.
6.Dependency Resolution Issue-npm ERR! Could not resolve dependency: peer react@"^16.0.0" from react-facebook-login@4.1.1
7.useNavigate Not Found in react-router-dom -export 'useNavigate' (imported as 'useNavigate') was not found in 'react-router-dom'
8.Replacing HashRouter with BrowserRouter: You have currently used HashRouter in your project and i want you to replace it with create BrowserRouter. 

### What is expected?
Want to start a project without any error . 
Solve all the issue that I am facing .

### What is actually happening?
1.Issue with sidenavCollapse.js-Line 123:32: 'info' is not defined.
2.React Hook useContext Called Conditionally.
3.Stylis Plugin RTL Warning -
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js): Failed to parse source map from '/home/thinkpad/frontendvision/node_modules/stylis-plugin-rtl/src/stylis-rtl.ts' file: Error: ENOENT: no such file or directory, open '/home/thinkpad/frontendvision/node_modules/stylis-plugin-rtl/src/stylis-rtl.ts'.
4.Module Warning for React Tag Input.
5.Module Not Found Error for VuiEditor.
6.Dependency Resolution Issue-npm ERR! Could not resolve dependency: peer react@"^16.0.0" from react-facebook-login@4.1.1
7.useNavigate Not Found in react-router-dom -export 'useNavigate' (imported as 'useNavigate') was not found in 'react-router-dom'
8.Replacing HashRouter with BrowserRouter: You have currently used HashRouter in your project and i want you to replace it with create BrowserRouter. 

---

**Comment by simmmpleweb** [comment]
Hello, @Naanncy ! Thanks for supporting our product! Can you tell us what package manager are you using?(and your current version of it?)
Regards, Vlad.

**Comment by Naanncy** [comment]
Yes I am using node 20 version . And also library used for globe i.e three
is not supported in that and i m facing other issue also . In this you have
use previous version of react-router dom which supports useHistory instead
of useNavigate . How I can change the route .

**Comment by simmmpleweb** [comment]
Can you please post some screenshots or logs? About half of the problems issued above do not appear in my version. Also about the HashRouter, you can directly change it, it should work just fine.

**Comment by Naanncy** [comment]
I want some more pages design
Like home page ,about us page , contact page
I want the figma of all the pages
And I m replacing hashrouting then it is not working I m not able to
navigate any other page only default dashboard is shown.
And globe package is giving error .

**Comment by Naanncy** [comment]
Hlo
I hope this email finds you well

I would like to request some additional pages to be added to the theme,
specifically the following:

   1. Home Page
   2. About Us
   3. Contact us

Could you please assist me in incorporating these pages into the theme?

**Comment by simmmpleweb** [comment]
Hello, @Naanncy ! The product archive has been updated. There are few things to be noted:
- Be sure to change the dependencies according to the versions used in the new archive
- Make sure that you use root.render
- Use the following structure for your routes :
```
{
    type: 'collapse',
    name: 'Dashboards',
    key: 'dashboards',
    icon: <IoHome size="15px" color="inherit" />,
    collapse: [
      {
        name: 'Home Page',
        layout: '/admin',
        path: '/home',
        component: <Home />,
      },
      {
        name: 'About Us', 
        layout: '/admin',
        path: '/about-us',
        component: <AboutUs />,
      },
      {
        name: 'Contact us', 
        layout: '/admin',
        path: '/contact-us',
        component: <ContactUs />,
      },
    ],
  },
```

**Comment by Naanncy** [comment]
Hello,

Thank you for your prompt response and for updating the product archive.

I appreciate the instructions provided. I will make sure to adjust the
dependencies according to the versions used in the new archive, and use
root.render as suggested.

Regarding the route structure, I will follow the specified format. If I
encounter any issues or have further questions during the implementation, I
will reach out for assistance.

But
I would like to request some additional pages to be added to the theme,
specifically the following:

Home Page
About Us
Contact us
Could you please assist me in incorporating design of these pages into the
theme either provide me the figma of these pages.?

Best regards,
Nancy

**Comment by Naanncy** [comment]
HI Team,

I am in need of figma design for Home, about us, contact us page
can you please provide designs for it

Quick response will be highly appreciated

**Comment by simmmpleweb** [comment]
This is a feature request. We would appreciate if you open a feature request issue, as shown in the issue template. We will take this into consideration and will add it on our todo list, however, we cannot give a timeline for this update as of now .
Regards, Vlad.
